name: Regression End-to-end tests
on: push
jobs:
  Add-ToCart-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
            command: npm run test:addToCart

      - name: Cypress Test Report
        uses: actions/upload-artifact@v7
        with:
            name: Mochawesome HTML Report for Add to Cart
            path: cypress/reports/html

  Reg-flow-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
            command: npm run test:registerFlow
            
      - name: Cypress Test Report
        uses: actions/upload-artifact@v7
        with:
            name: Mochawesome HTML Report for Register flow
            path: cypress/reports/html